version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"  # zmieniony z 5000:5000 na 5001:5000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
